-- MySQL Script generated by MySQL Workbench
-- Sun Sep 20 16:08:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cataleg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cataleg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cataleg` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema xarxa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xarxa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xarxa` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET latin1 ;
USE `cataleg` ;

-- -----------------------------------------------------
-- Table `cataleg`.`llibre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataleg`.`llibre` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `stock` INT(250) NOT NULL,
  `Preu` DOUBLE(100,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cataleg`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataleg`.`autor` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `llibre_id` INT(10) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `direccio` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_autor_llibre` (`llibre_id` ASC) VISIBLE,
  CONSTRAINT `fk_autor_llibre`
    FOREIGN KEY (`llibre_id`)
    REFERENCES `cataleg`.`llibre` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cataleg`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataleg`.`usuario` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(250) NOT NULL,
  `email` VARCHAR(15) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cataleg`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cataleg`.`compras` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `llibre_id` INT(10) NOT NULL,
  `usuario_id` INT(10) NOT NULL,
  `observaciones` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` INT(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compras_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_compras_llibre` (`llibre_id` ASC) VISIBLE,
  CONSTRAINT `fk_compras_llibre`
    FOREIGN KEY (`llibre_id`)
    REFERENCES `cataleg`.`llibre` (`id`),
  CONSTRAINT `fk_compras_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cataleg`.`usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;

USE `xarxa` ;

-- -----------------------------------------------------
-- Table `xarxa`.`fotografias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xarxa`.`fotografias` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `identificador` VARCHAR(100) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `xarxa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xarxa`.`usuario` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `fotografias_id` INT(10) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(15) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_fotografias` (`fotografias_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_fotografias`
    FOREIGN KEY (`fotografias_id`)
    REFERENCES `xarxa`.`fotografias` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;

USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`ulleres` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(100) NOT NULL,
  `modelo` VARCHAR(150) NOT NULL,
  `graduacio` VARCHAR(100) NOT NULL,
  `montura` VARCHAR(100) NOT NULL,
  `color_montura` VARCHAR(100) NOT NULL,
  `color_vidrio` VARCHAR(100) NOT NULL,
  `precio` DOUBLE(100,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `optica`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`vendedor` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `optica`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`client` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `ulleres_id` INT(10) NOT NULL,
  `vendedor_id` INT(10) NOT NULL,
  `Nom` VARCHAR(100) NOT NULL,
  `Adreca` VARCHAR(150) NOT NULL,
  `telefon` VARCHAR(150) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `data_registre` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_ulleres` (`ulleres_id` ASC) VISIBLE,
  INDEX `fk_client_vendedor_idx` (`vendedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_ulleres`
    FOREIGN KEY (`ulleres_id`)
    REFERENCES `optica`.`ulleres` (`id`),
  CONSTRAINT `fk_client_vendedor`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `optica`.`vendedor` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `optica`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`proveedor` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `factura_id` INT(10) NOT NULL,
  `Nom` VARCHAR(250) NOT NULL,
  `Nif` VARCHAR(150) NOT NULL,
  `carrer` VARCHAR(100) NOT NULL,
  `numero` INT(10) NOT NULL,
  `pis` VARCHAR(50) NULL DEFAULT NULL,
  `porta` INT(10) NULL DEFAULT NULL,
  `ciutat` VARCHAR(100) NOT NULL,
  `codi_postal` INT(50) NOT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `telefon` INT(150) NOT NULL,
  `fax` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `optica`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`facturas` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `ulleres_id` INT(10) NOT NULL,
  `proveedor_id` INT(10) NOT NULL,
  `Nom` VARCHAR(100) NOT NULL,
  `Adreca` VARCHAR(150) NOT NULL,
  `telefon` VARCHAR(150) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `data_registre` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facturas_proveedor` (`proveedor_id` ASC) VISIBLE,
  INDEX `fk_facturas_ulleres` (`ulleres_id` ASC) VISIBLE,
  CONSTRAINT `fk_facturas_proveedor`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `optica`.`proveedor` (`id`),
  CONSTRAINT `fk_facturas_ulleres`
    FOREIGN KEY (`ulleres_id`)
    REFERENCES `optica`.`ulleres` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
